name: Dependascarbabot
on:
  workflow_dispatch:

jobs:
  dependascarbabot:
    runs-on: ubuntu-latest
    steps:
      - uses: cwastche/dependascarbabot@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          scarb-version: 2.5.2