name: Dependascarbabot
on:
  workflow_dispatch:

jobs:
  dependascarbabot:
    runs-on: ubuntu-latest
    steps:
      - uses: cwastche/dependascarbabot@v1
        with:
          fine-grained-token: ${{ secrets.FINE_GRAINED_TOKEN }}
          # Or use github-app-token: ${{ secrets.GITHUB_APP_TOKEN }}
          scarb-version: 2.5.2